// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzbjugabndesaikxgtpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6Ymp1Z2FibmRlc2Fpa3hndHBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTU4ODgsImV4cCI6MjA2MjgzMTg4OH0.l4MQSMXnweC1I5dw5KjcgGXqZxyOxyLMVXQe24lQGkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);